### PR TITLE
Return the version of bcl2fastq running on start

### PR DESCRIPTION
**Pull request by johandahlberg**
Return the version of bcl2fastq and the arteria-bcl2fastq versions when starting a new job.

### CODE REVIEW

**Comment by johanherman** [comment]
Looks good, but perhaps the tests should pass first?

**Comment by johandahlberg** [comment]
Agreed. Will fix the tests - I think some changes in arteria-core broke it.

**Comment by johandahlberg** [comment]
It's fixed now.

**Comment by johanherman** [comment]
:+1:

**Pull request merged**
